name: Request Software Access
description: Submit this form to request per-user software access
title: "Access Request: "
labels: ["access-request"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill this form to request access.
        Access is granted **per-user** and will be valid for **1 year** from approval.
        After expiry, users may submit a renewal request.

        **Please cite this work if you use the software**:
        "A molecular dynamics postprocessing tool for analyzing the structure and dynamics of materials,
        M K Gupta, Computer Physics Communications 320 (2026) 109982,
        doi:https://doi.org/10.1016/j.cpc.2025.109982"

  - type: input
    id: name
    attributes:
      label: Full Name
    validations:
      required: true

  - type: input
    id: designation
    attributes:
      label: Designation / Position
      placeholder: e.g., Research Scholar, Scientist, Faculty, Engineer
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization / Institution
    validations:
      required: true

  - type: input
    id: country
    attributes:
      label: Country
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Official / Institutional Email Address
      placeholder: name@institution.org
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose of Software Use
      description: Briefly describe your project / research application
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Access & Usage Declaration
      options:
        - label: I understand that access is granted on a **per-user basis** and must not be shared or transferred
          required: true
        - label: I agree not to redistribute or publish the software without prior permission
          required: true
        - label: I acknowledge that access will be valid for **1 year** and renewal will be required thereafter
          required: true
        - label: Please cite the above publication if you use this software
          required: false

          
